Repository api-ghost/api-ghost-agent-spring, pull requests merged in 2025-05, with the labels that each got.

#9 feat(agent): Importing a core module into a web module
  build.gradle
  gradlew
  web/build.gradle
  web/src/main/java/com/apighost/agent/config/ApiGhostProperties.java
  web/src/main/java/com/apighost/agent/config/ApiGhostWebAutoConfiguration.java
  web/src/main/java/com/apighost/agent/controller/EndPointProvider.java
  web/src/main/resources/static/apighost-ui.html
Labels: 0.0.1 - BETA, feature

#13 feat(web): implement scenario test feature
  web/build.gradle
  web/src/main/java/com/apighost/agent/config/ApiGhostWebAutoConfiguration.java
  web/src/main/java/com/apighost/agent/controller/EngineController.java
  web/src/main/java/com/apighost/agent/executor/ResponseResult.java
  web/src/main/java/com/apighost/agent/executor/ScenarioTestExecutor.java
  web/src/main/java/com/apighost/agent/loader/ScenarioFileLoader.java
  web/src/main/resources/application.properties
  web/src/main/resources/static/apighost-ui.html
Labels: 0.0.1 - BETA, feature

#10 feat(core): implementing collecting requestSchema and convert to json
  core/src/main/java/com/apighost/agent/collector/ApiCollector.java
  core/src/main/java/com/apighost/agent/model/DtoSchema.java
  core/src/main/java/com/apighost/agent/model/EndPoint.java
  core/src/main/java/com/apighost/agent/model/EndPointJson.java
  core/src/main/java/com/apighost/agent/model/FieldMeta.java
  core/src/main/java/com/apighost/agent/sender/EndpointJsonBodyConverter.java
Labels: 0.0.1 - BETA, feature

#15 refactor(core): convert HTTP method representation from String to Enum for …
  core/build.gradle
  core/src/main/java/com/apighost/agent/collector/ApiCollector.java
  core/src/main/java/com/apighost/agent/model/EndPoint.java
  core/src/main/java/com/apighost/agent/model/EndPointJson.java
Labels: 0.0.1 - BETA, feature

#18 hotfix: Added missing import (java.util.Arrays)
  core/src/main/java/com/apighost/agent/collector/ApiCollector.java
Labels: 0.0.1 - BETA

#16 feat(web): scenario-list, result-list API Development
  web/build.gradle
  web/src/main/java/com/apighost/agent/config/ApiGhostSetting.java
  web/src/main/java/com/apighost/agent/config/ApiGhostWebAutoConfiguration.java
  web/src/main/java/com/apighost/agent/controller/EngineController.java
  web/src/main/java/com/apighost/agent/engine/FileLoaderEngine.java
  web/src/main/java/com/apighost/agent/executor/ScenarioTestExecutor.java
  web/src/main/java/com/apighost/agent/loader/FileLoader.java
  web/src/main/java/com/apighost/agent/model/ResponseResult.java
  web/src/main/java/com/apighost/agent/model/ScenarioListResponse.java
  web/src/main/java/com/apighost/agent/model/ScenarioResultBrief.java
  web/src/main/java/com/apighost/agent/model/ScenarioResultListResponse.java
  web/src/main/resources/apighost-settings.properties
  web/src/main/resources/application.properties
Labels: 0.0.1 - BETA, feature

#23 feat(web): Implement API to query file details
  web/src/main/java/com/apighost/agent/config/ApiGhostWebAutoConfiguration.java
  web/src/main/java/com/apighost/agent/controller/EngineController.java
  web/src/main/java/com/apighost/agent/engine/FileLoaderEngine.java
Labels: 0.0.1 - BETA, feature

#20 feat(core): Update EndPoint schema and add responseSchema collection logic
  core/src/main/java/com/apighost/agent/collector/ApiCollector.java
  core/src/main/java/com/apighost/agent/model/EndPoint.java
Labels: 0.0.1 - BETA, feature

#25 feat(core): add parameter collection logic and restructure endpoint with builder pattern
  core/src/main/java/com/apighost/agent/collector/ApiCollector.java
  core/src/main/java/com/apighost/agent/model/DtoSchema.java
  core/src/main/java/com/apighost/agent/model/EndPoint.java
  core/src/main/java/com/apighost/agent/model/EndPointJson.java
  core/src/main/java/com/apighost/agent/model/FieldMeta.java
  core/src/main/java/com/apighost/agent/model/Parameter.java
  core/src/main/java/com/apighost/agent/sender/EndpointJsonBodyConverter.java
  web/build.gradle
  web/src/main/java/com/apighost/agent/config/ApiGhostProperties.java
  web/src/main/java/com/apighost/agent/config/ApiGhostWebAutoConfiguration.java
Labels: 0.0.1 - BETA, feature

#26 feat(web): Implement Export Scenario Result file
  web/src/main/java/com/apighost/agent/config/ApiGhostWebAutoConfiguration.java
  web/src/main/java/com/apighost/agent/engine/FileLoaderEngine.java
  web/src/main/java/com/apighost/agent/executor/ScenarioTestExecutor.java
  web/src/main/java/com/apighost/agent/loader/FileExporter.java
  web/src/main/java/com/apighost/agent/model/ResponseResult.java
  web/src/main/java/com/apighost/agent/util/TimeUtils.java
Labels: 0.0.1 - BETA, feature

#28 feat(web): Implement Scenario test sub - function
  web/src/main/java/com/apighost/agent/executor/ScenarioTestExecutor.java
  web/src/main/resources/static/apighost-ui.html
Labels: 0.0.1 - BETA, feature

#35 refactor(web): Refactored scenario test execution code
  web/src/main/java/com/apighost/agent/config/ApiGhostWebAutoConfiguration.java
  web/src/main/java/com/apighost/agent/controller/EngineController.java
  web/src/main/java/com/apighost/agent/engine/FileLoaderEngine.java
  web/src/main/java/com/apighost/agent/executor/HttpExecutor.java
  web/src/main/java/com/apighost/agent/executor/ScenarioTestExecutor.java
  web/src/main/java/com/apighost/agent/file/FileExporter.java
  web/src/main/java/com/apighost/agent/notifier/ResultSseNotifier.java
  web/src/main/java/com/apighost/agent/notifier/ScenarioResultNotifier.java
  web/src/main/java/com/apighost/agent/orchestrator/ScenarioTestOrchestrator.java
  web/src/main/java/com/apighost/agent/util/ExecutionTimer.java
  web/src/main/java/com/apighost/agent/util/HttpRequestBuilder.java
  web/src/main/java/com/apighost/agent/util/ObjectMapperHolder.java
  web/src/main/java/com/apighost/agent/util/YamlMapperHolder.java
Labels: 0.0.1 - BETA, refactor

#38 feat(web): Implement generate data API
  libs/generator-1.0-SNAPSHOT.jar
  libs/model-1.0-SNAPSHOT.jar
  web/build.gradle
  web/src/main/java/com/apighost/agent/config/ApiGhostWebAutoConfiguration.java
  web/src/main/java/com/apighost/agent/controller/EngineController.java
  web/src/main/java/com/apighost/agent/file/ScenarioFileLoader.java
  web/src/main/resources/static/apighost-ui.html
Labels: 0.0.1 - BETA, feature

#40 feat(web): Add file name into file detail response
  web/src/main/java/com/apighost/agent/engine/FileLoaderEngine.java
  web/src/main/java/com/apighost/agent/model/GenericFileDetailResponse.java
Labels: 0.0.1 - BETA, feature

#42 feat(web): Added GlobalExceptionHandler
  web/src/main/java/com/apighost/agent/config/ApiGhostWebAutoConfiguration.java
  web/src/main/java/com/apighost/agent/exception/ErrorCode.java
  web/src/main/java/com/apighost/agent/exception/ErrorResponse.java
  web/src/main/java/com/apighost/agent/exception/GlobalExceptionHandler.java
Labels: 0.0.1 - BETA, feature

#43 feat(web): Add some function(timeout ms, etc)
  web/src/main/java/com/apighost/agent/config/ApiGhostWebAutoConfiguration.java
  web/src/main/java/com/apighost/agent/executor/HttpExecutor.java
  web/src/main/java/com/apighost/agent/executor/ScenarioTestExecutor.java
  web/src/main/java/com/apighost/agent/model/ResponseResult.java
Labels: bug, 0.0.1 - BETA, feature

#45 refactor(web): Apply web socket, scenario test using core module
  libs/core-1.0-SNAPSHOT.jar
  libs/generator-1.0-SNAPSHOT.jar
  libs/model-1.0-SNAPSHOT.jar
  libs/parser-1.0-SNAPSHOT.jar
  web/build.gradle
  web/src/main/java/com/apighost/agent/config/ApiGhostWebAutoConfiguration.java
  web/src/main/java/com/apighost/agent/executor/HttpExecutor.java
  web/src/main/java/com/apighost/agent/executor/ScenarioTestExecutor.java
  web/src/main/resources/static/apighost-ui.html
Labels: 0.0.1 - BETA, feature

#48 feat(web): Implement file remove API and file remover
  web/src/main/java/com/apighost/agent/config/ApiGhostWebAutoConfiguration.java
  web/src/main/java/com/apighost/agent/controller/EngineController.java
  web/src/main/java/com/apighost/agent/engine/FileLoaderEngine.java
  web/src/main/java/com/apighost/agent/file/FileRemover.java
  web/src/main/java/com/apighost/agent/file/ScenarioFileLoader.java
  web/src/main/java/com/apighost/agent/orchestrator/ScenarioTestOrchestrator.java
Labels: 0.0.1 - BETA, feature

#49 hotfix(core): Convert List<FieldMeta> and List<Parameter> to JSON using ObjectMapper
  core/src/main/java/com/apighost/agent/collector/ApiCollector.java
  core/src/main/java/com/apighost/agent/collector/converter/EndpointJsonBodyConverter.java
  libs/model-1.0-SNAPSHOT.jar
Labels: 0.0.1 - BETA, hotfix

#52 fix(web): Prevent error throw in sse communication
  libs/core-1.0-SNAPSHOT.jar
  libs/generator-1.0-SNAPSHOT.jar
  libs/model-1.0-SNAPSHOT.jar
  libs/parser-1.0-SNAPSHOT.jar
  web/src/main/java/com/apighost/agent/exception/GlobalExceptionHandler.java
  web/src/main/java/com/apighost/agent/notifier/ResultSseNotifier.java
Labels: bug, 0.0.1 - BETA

#53 feat(core): add collecting-websocket-url
  core/build.gradle
  core/src/main/java/com/apighost/agent/collector/ApiCollector.java
  core/src/main/java/com/apighost/agent/collector/Collector.java
  core/src/main/java/com/apighost/agent/collector/RestApiCollector.java
  core/src/main/java/com/apighost/agent/collector/WebSocketCollector.java
  core/src/main/java/com/apighost/agent/collector/converter/JsonEndpointConverter.java
  core/src/main/java/com/apighost/agent/collector/util/EndpointUtil.java
  core/src/main/java/com/apighost/agent/collector/util/WebSocketAnalyzerUtil.java
  web/src/main/java/com/apighost/agent/config/ApiGhostWebAutoConfiguration.java
  web/src/main/java/com/apighost/agent/controller/EndPointProvider.java
  web/src/main/java/com/apighost/agent/exception/GlobalExceptionHandler.java
Labels: 0.0.1 - BETA, feature

#54 fix(web): Return by specifying the header of the data to match the client request
  web/src/main/java/com/apighost/agent/exception/GlobalExceptionHandler.java
Labels: 0.0.1 - BETA

#55 fix(core): Modifying what you were collecting even though you didn't have a WebSocket setup
  core/src/main/java/com/apighost/agent/collector/WebSocketCollector.java
  core/src/main/java/com/apighost/agent/collector/util/WebSocketAnalyzerUtil.java
Labels: 0.0.1 - BETA

#56 hotfix: add setting statement for bootJar scanning and classgraph version up
  core/build.gradle
  core/src/main/java/com/apighost/agent/collector/util/EndpointUtil.java
Labels: bug, 0.0.1 - BETA

#57 fix(core): websocket-subscribe-target
  core/src/main/java/com/apighost/agent/collector/WebSocketCollector.java
  core/src/main/java/com/apighost/agent/collector/util/EndpointUtil.java
Labels: enhancement, 0.0.1 - BETA

#58 feat(web): implement directory initializer
  web/build.gradle
  web/src/main/java/com/apighost/agent/controller/ScenarioGUIController.java
  web/src/main/java/com/apighost/agent/file/DirectoryInitializer.java
Labels: 0.0.1 - BETA, feature

#59 fix(core): collecting Change how WebSocket Settings classes are collected
  core/build.gradle
  core/src/main/java/com/apighost/agent/collector/WebSocketCollector.java
  core/src/main/java/com/apighost/agent/collector/util/WebSocketAnalyzerUtil.java
Labels: enhancement, 0.0.1 - BETA
